# Generated by Django 4.0 on 2024-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
