name: Release

on:
    push:
      branches:
        - 'main'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install uv and dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source "$HOME/.cargo/env"
        # Install build/dev dependencies needed for release
        uv pip install --system .[dev]
    - name: Build and release
      run: |
        python -m build
        twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
